name: End-to-end tests
on: [ push ]
jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: setup node
        with:
          node-version: '13.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install currents
        run: npm i @currents/cli

      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          command: npm run run:currents -- --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"
